### ISSUE TITLE
Issues with returning maped nested Observers

### ISSUE THREAD

**Issue by torrinworx** [Nefsen402/destam-dom#4]
I noticed some issues when trying to return a mapped observer nested in an OObject with v10.2, not sure if this is the only case that's effected:
```
const Pages = ({ state }) => {
    const openPage = state.client.observer.path('openPage');

    return openPage.map((p) => {
        // ... (logic in here never runs)
    })
};

const state = OObject({
    client: OObject({
        openPage: {
            page: 'Home'
        }
    })
});

mount(document.body, <Pages state={state} />);
```

When this runs it doesn't render the component and returns this:
```
Caused by: Error: Objects passed to destam-dom must be iterable (like arrays). Maybe you passed in a raw object?
```

This issue fixes itself if I revert back to [v0.9.2](https://github.com/Nefsen402/destam-dom/releases/tag/v0.9.2)

**Comment by torrinworx** [comment]
Ah ok nevermind, the cause seems be related to the difference between destam vs destam-dom OObjects:

import { OObject } from 'destam-dom'
// import { OObject } from "destam";

Where the error crops up when using destam/Object

**Comment by torrinworx** [comment]
Actually I'm gonna need to re-open this, it seems this has broader effects. In the below example I have a client side state helper that stores observer state in indexeddb in the browser, since the client isn't able to handle returning destam OObjects in components anymore, this means I must use destam-dom OObjects to store state. But that's not really possible since destam-dom OObjects don't have any tracking info, so the parse/stringify methods used here just convert it into a normal js object and the observability is lost:
```javascript

export const ODB = async (driver, collection, query, value = OObject({})) => {
	driver = drivers[driver]
	const { state_tree, id } = await driver.init(collection, query, value)

	if (state_tree) {
		const state = parse(JSON.stringify(state_tree));
		state.observer.watch(async () => {
			await driver.update(collection, id, state)
		});
		return state;
	} else return false;
};

// Example:
// import { OObject } from 'destam-dom';

// works with ODB, but returns "Caused by: Error: Objects passed to destam-dom must be iterable (like arrays).
// Maybe you passed in a raw object?" in mount() below:
import { OObject } from 'destam'; 
const client = await ODB('indexeddb', 'client', {}, OObject({ state: 'client' }))

mount(document.body, client.observer.path('state').map(s => s ? s : 'no state'))
```

The above ODB function is from here: https://github.com/torrinworx/destam-db-core/blob/d2d7fc037b7f4bc322994db79bd9b450b19dda59/odb.js#L73C1-L73C79

I'm not really sure what the best way to resolve this is, would love to know if there is something I'm missing from my approach. Ideally it would be nice if components could return values from a destam OObject like in previous versions

**Comment by Nefsen402** [comment]
This sounds like an issue with your build environment. It sounds like you’re running two versions of destam that are conflicting. Double check the node modules folder for a duplicate.

Running `npm i destam@latest destam-dom@latest` might resolve the issue. Another thing to check is to make sure destamatic-ui isn’t pulling down an older version.

**Comment by torrinworx** [comment]
Aaaaaah yeah that was totally it lol, double checking the packages solved that, thanks Alex!
